export const WORD_BANKS = {
  "3": [
    "THE", "AND", "FOR", "YOU", "NOT", "ARE", "ALL", "NEW", "WAS", "CAN",
    "HAS", "BUT", "OUR", "ONE", "MAY", "OUT", "USE", "ANY", "SEE", "HIS",
    "WHO", "WEB", "NOW", "GET", "HOW", "ITS", "TOP", "HAD", "DAY", "TWO",
    "BUY", "HER", "ADD", "JAN", "SHE", "SEX", "SET", "MAP", "WAY", "OFF",
    "DID", "CAR", "DVD", "OWN", "END", "HIM", "PER", "BIG", "LAW", "ART",
    "USA", "OLD", "NON", "WHY", "LOW", "MAN", "JOB", "TOO", "MEN", "BOX",
    "GAY", "AIR", "YES", "HOT", "SAY", "DEC", "SAN", "TAX", "GOT", "LET",
    "ACT", "RED", "KEY", "FEW", "AGE", "OCT", "PAY", "WAR", "NOV", "FAX",
    "YET", "SUN", "RSS", "RUN", "NET", "PUT", "TRY", "GOD", "LOG", "FAQ",
    "FUN", "FEB", "SEP", "LOT", "ASK", "DUE", "MAR", "PRO", "URL", "AUG",
    "AGO", "APR", "VIA", "BAD", "FAR", "JUL", "JUN", "OIL", "BIT", "BAY",
    "BAR", "DOG", "EUR", "PDF", "USR", "MON", "COM", "GAS", "SIX", "PRE",
    "SAT", "ZIP", "BID", "FRI", "WED", "INN", "LTD", "LOS", "INC", "WIN",
    "BED", "TUE", "ASS", "THU", "SEA", "CUT", "TEL", "KIT", "BOY", "EST",
    "SON", "MAC", "III", "GMT", "MAX", "XML", "BIN", "VAN", "ADS", "POP",
    "INT", "HIT", "EYE", "USB", "PHP", "ETC", "MSN", "FEE", "LAS", "MIN",
    "AID", "FAT", "SAW", "PST", "XXX", "TOM", "SUB", "LED", "FAN", "TEN",
    "CAT", "DIE", "PET", "GUY", "DEV", "CUP", "VOL", "LEE", "BOB", "FIT",
    "MET", "WWW", "CUM", "ICE", "LLC", "SEC", "BUS", "BAG", "IBM", "NOR",
    "BUG", "MID", "JIM", "DEL", "JOE", "CDS", "LAB", "CVS", "DES", "LCD",
    "AVE", "PIC", "TAG", "MIX", "VHS", "FIX", "RAY", "DRY", "SPA", "CON",
    "UPS", "VAR", "WON", "DOC", "MOM", "ROW", "USD", "EAT", "AIM", "LES",
    "ANN", "TIP", "SKI", "DAN", "FLY", "HEY", "BBC", "TEA", "AVG", "SKY",
    "ROM", "TOY", "SRC", "HIP", "DOT", "HIV", "PDA", "DSL", "ZUM", "DNA",
    "TIM", "SQL", "DON", "GPS", "ACC", "CAP", "INK", "PIN", "RAW", "GNU"
  ],
  "4": [
    "THAT", "THIS", "WITH", "FROM", "YOUR", "HAVE", "MORE", "WILL", "HOME",
    "PAGE", "FREE", "TIME", "THEY", "SITE", "NEWS", "ONLY", "WHEN", "HERE",
    "ALSO", "HELP", "VIEW", "BEEN", "WERE", "SOME", "LIKE", "THAN", "FIND",
    "DATE", "BACK", "LIST", "NAME", "JUST", "OVER", "YEAR", "INTO", "NEXT",
    "USED", "WORK", "LAST", "MOST", "DATA", "MAKE", "THEM", "POST", "CITY",
    "SUCH", "BEST", "THEN", "GOOD", "WELL", "INFO", "HIGH", "EACH", "VERY",
    "BOOK", "READ", "NEED", "MANY", "USER", "SAID", "DOES", "MAIL", "FULL",
    "LIFE", "KNOW", "DAYS", "PART", "REAL", "ITEM", "EBAY", "MUST", "MADE",
    "LINE", "SEND", "TYPE", "TAKE", "AREA", "WANT", "LONG", "CODE", "SHOW",
    "EVEN", "MUCH", "SIGN", "FILE", "LINK", "OPEN", "CASE", "SAME", "BOTH",
    "GAME", "CARE", "DOWN", "SIZE", "SHOP", "TEXT", "RATE", "FORM", "LOVE",
    "JOHN", "MAIN", "CALL", "SAVE", "YORK", "CARD", "JOBS", "FOOD", "SALE",
    "TEEN", "ROOM", "JOIN", "WEST", "LOOK", "LEFT", "TEAM", "WEEK", "NOTE",
    "LIVE", "JUNE", "PLAN", "COST", "JULY", "TEST", "CART", "TRUE", "STEP",
    "AWAY", "BASE", "GIVE", "FISH", "BLUE", "BODY", "DEEP", "ROAD", "FALL",
    "FIVE", "EASY", "FOUR", "HAND", "KEEP", "BABY", "LAND", "MIND", "PAID",
    "FACE", "HEAD", "SURE", "SORT", "FAST", "LAST", "FIRE", "WIND", "GOLD",
    "IRON", "WAVE", "WOOD", "RAIN", "DARK", "LEFT", "RIGHT", "SOFT", "HARD",
    "NEAR", "SIDE", "WIDE", "TALL", "COLD", "HEAT", "FIRE", "SNOW", "STAR"
  ],
  "5": [
    "ABOUT", "OTHER", "WHICH", "THEIR", "THERE", "FIRST", "WOULD", "THESE",
    "CLICK", "PRICE", "STATE", "EMAIL", "WORLD", "MUSIC", "AFTER", "VIDEO",
    "WHERE", "BOOKS", "LINKS", "YEARS", "ORDER", "ITEMS", "GROUP", "UNDER",
    "GAMES", "COULD", "GREAT", "HOTEL", "STORE", "TERMS", "RIGHT", "LOCAL",
    "THOSE", "USING", "PHONE", "DATA", "STUDY", "SMALL", "STILL", "BOARD",
    "STEAM", "TRIED", "WIDTH", "APPLE", "GHOST", "SHINE", "LEVEL", "HEART",
    "SOUND", "POINT", "SPACE", "POWER", "LIGHT", "WATER", "NIGHT", "STREET",
    "HOUSE", "TABLE", "PLACE", "SMILE", "WRITE", "STORY", "THING", "THINK",
    "CLOCK", "BREAD", "FRUIT", "GRASS", "GREEN", "PAPER", "PILOT", "PIZZA",
    "PLANE", "PLANT", "RIVER", "SNAKE", "SPIDE", "SPORT", "TRAIN", "TRUCK",
    "VOICE", "WITCH", "WORLD", "WATCH", "WOMEN", "MUSIC", "CLEAR", "TOUCH",
    "READY", "IMAGE", "MEDIA", "SMALL", "LARGE", "EXTRA", "QUICK", "SCORE",
    "BOARD", "TOTAL", "START", "SOUND", "LEVEL", "CHILD"
  ],
  "6": [
    "SEARCH", "ONLINE", "PEOPLE", "HEALTH", "SHOULD", "SYSTEM", "POLICY",
    "NUMBER", "PLEASE", "REVIEW", "PUBLIC", "SCHOOL", "THINGS", "CENTER",
    "REPORT", "BEFORE", "THROUGH", "OTHERS", "AROUND", "SECOND", "ORANGE",
    "VIOLET", "YELLOW", "SILVER", "BRIGHT", "SCREEN", "BUTTON", "WINDOW",
    "RECORD", "ACTIVE", "WIDGET", "DELETE", "FORMAT", "UPDATE", "INSERT",
    "RELOAD", "FINISH", "CANCEL", "SUBMIT", "SELECT", "REMOVE", "CREATE",
    "EXPORT", "IMPORT", "UPLOAD", "SERVER", "CLIENT", "FRIEND", "SCHOOL",
    "FAMILY", "GARDEN", "MARKET", "OFFICE", "PLANET", "PLAYER", "ROCKET"
  ]
};
